CREATE TABLE report_events (
    event_id UUID PRIMARY KEY,
    order_id BIGINT NOT NULL CHECK (order_id > 0),
    aggregate_version BIGINT NOT NULL CHECK (aggregate_version > 0),
    payload TEXT NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (order_id, aggregate_version)
);

CREATE TABLE report_orders (
    order_id BIGINT PRIMARY KEY CHECK (order_id > 0),
    aggregate_version BIGINT NOT NULL CHECK (aggregate_version > 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('CREADO', 'ACEPTADO', 'EN_PREPARACION', 'DESPACHADO', 'ENTREGADO', 'CANCELADO')),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    total NUMERIC(19, 2) NOT NULL CHECK (total > 0),
    CHECK (occurred_at >= created_at)
);
CREATE INDEX idx_report_delivered_hour ON report_orders(occurred_at) WHERE status = 'ENTREGADO';

CREATE TABLE report_rejections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_topic VARCHAR(249) NOT NULL,
    source_partition INTEGER NOT NULL,
    source_offset BIGINT NOT NULL,
    reason VARCHAR(40) NOT NULL,
    payload_sha256 VARCHAR(64) NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_topic, source_partition, source_offset)
);
