-- Boletas generadas desde el comando RabbitMQ invoice.gen (una por pedido entregado).
-- event_id y order_id únicos hacen idempotente el consumo ante reentregas o reprocesos desde la DLQ.
CREATE TABLE report_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL UNIQUE,
    order_id BIGINT NOT NULL UNIQUE CHECK (order_id > 0),
    customer_id VARCHAR(200) NOT NULL,
    folio VARCHAR(30) NOT NULL UNIQUE,
    net_amount NUMERIC(19, 2) NOT NULL CHECK (net_amount > 0),
    tax_amount NUMERIC(19, 2) NOT NULL CHECK (tax_amount >= 0),
    total_amount NUMERIC(19, 2) NOT NULL CHECK (total_amount > 0),
    item_count INTEGER NOT NULL CHECK (item_count BETWEEN 1 AND 50),
    document TEXT NOT NULL,
    trace_id VARCHAR(100) NOT NULL,
    issued_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CHECK (net_amount + tax_amount = total_amount)
);
