CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id VARCHAR(200) NOT NULL,
    status VARCHAR(30) NOT NULL,
    pending_status VARCHAR(30),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    total NUMERIC(24,2) NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    CONSTRAINT ck_orders_customer CHECK (CHAR_LENGTH(TRIM(customer_id)) > 0),
    CONSTRAINT ck_orders_total CHECK (total > 0),
    CONSTRAINT ck_orders_status CHECK (status IN ('CREADO','ACEPTADO','EN_PREPARACION','DESPACHADO','ENTREGADO','CANCELADO')),
    CONSTRAINT ck_orders_pending CHECK (pending_status IS NULL OR
        (status = 'CREADO' AND pending_status = 'ACEPTADO') OR
        (status = 'ACEPTADO' AND pending_status = 'CANCELADO'))
);

CREATE INDEX ix_orders_customer ON purchase_orders(customer_id, id);

CREATE TABLE order_items (
    order_id BIGINT NOT NULL REFERENCES purchase_orders(id),
    line_number INTEGER NOT NULL,
    product_id BIGINT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price NUMERIC(12,2) NOT NULL,
    PRIMARY KEY (order_id, line_number),
    CONSTRAINT uq_order_product UNIQUE (order_id, product_id),
    CONSTRAINT ck_item_product CHECK (product_id > 0),
    CONSTRAINT ck_item_quantity CHECK (quantity > 0),
    CONSTRAINT ck_item_price CHECK (unit_price >= 0.01)
);
