ALTER TABLE purchase_orders ADD COLUMN event_version BIGINT NOT NULL DEFAULT 0;
ALTER TABLE purchase_orders ADD CONSTRAINT ck_order_event_version CHECK (event_version >= 0);

CREATE TABLE order_event_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(36) NOT NULL UNIQUE,
    order_id BIGINT NOT NULL REFERENCES purchase_orders(id) ON DELETE CASCADE,
    aggregate_version BIGINT NOT NULL CHECK (aggregate_version > 0),
    payload VARCHAR(4000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    published_at TIMESTAMP WITH TIME ZONE,
    attempts INTEGER NOT NULL DEFAULT 0 CHECK (attempts >= 0),
    next_attempt_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_order_event_version UNIQUE (order_id, aggregate_version)
);

CREATE INDEX ix_order_events_pending ON order_event_outbox(published_at, next_attempt_at, id);
