-- Tickets de cocina generados desde el comando RabbitMQ kitchen.ticket (uno por pedido).
-- event_id y order_id únicos hacen idempotente el consumo ante reentregas o reprocesos desde la DLQ.
CREATE TABLE kitchen_tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL,
    order_id BIGINT NOT NULL,
    customer_id VARCHAR(200) NOT NULL,
    trace_id VARCHAR(100) NOT NULL,
    item_count INTEGER NOT NULL,
    ticket_text VARCHAR(8000) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    CONSTRAINT uq_kitchen_tickets_event UNIQUE (event_id),
    CONSTRAINT uq_kitchen_tickets_order UNIQUE (order_id),
    CONSTRAINT ck_kitchen_tickets_order CHECK (order_id > 0),
    CONSTRAINT ck_kitchen_tickets_items CHECK (item_count BETWEEN 1 AND 50)
);
