spring.application.name=ms-pedidos360-catalog

# Puerto del microservicio
server.port=${CATALOG_PORT:8082}

# Exponer solamente el endpoint de salud por HTTP
management.endpoints.web.exposure.include=health

# No mostrar detalles internos de los componentes
management.endpoint.health.show-details=never
management.endpoint.health.show-components=never