CREATE TABLE audit_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id UUID NOT NULL UNIQUE,
    order_id BIGINT NOT NULL CHECK (order_id > 0),
    aggregate_version BIGINT NOT NULL CHECK (aggregate_version > 0),
    payload TEXT NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (order_id, aggregate_version)
);
CREATE INDEX idx_audit_order_cursor ON audit_events(order_id, id);

CREATE TABLE audit_rejections (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_topic VARCHAR(249) NOT NULL,
    source_partition INTEGER NOT NULL,
    source_offset BIGINT NOT NULL,
    reason VARCHAR(40) NOT NULL,
    payload_sha256 VARCHAR(64) NOT NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UNIQUE (source_topic, source_partition, source_offset)
);
