-- Copia auditada de cada dead letter de los comandos RabbitMQ (q.cmd.email, q.cmd.kitchen, q.cmd.invoice).
-- El mensaje original queda en su DLQ para reproceso; aquí se conserva el historial aunque la DLQ se purgue o expire.
CREATE TABLE audit_dead_letters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    message_id VARCHAR(200) NOT NULL,
    source_queue VARCHAR(255) NOT NULL,
    reason VARCHAR(40) NOT NULL,
    death_count BIGINT NOT NULL CHECK (death_count > 0),
    original_exchange VARCHAR(255),
    original_routing_key VARCHAR(255),
    message_type VARCHAR(100),
    correlation_id VARCHAR(200),
    trace_id VARCHAR(100),
    payload TEXT NULL,
    payload_sha256 VARCHAR(64) NOT NULL,
    payload_bytes INTEGER NOT NULL CHECK (payload_bytes >= 0),
    first_death_at TIMESTAMP WITH TIME ZONE NULL,
    recorded_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    -- Una reentrega del mismo rechazo no se duplica; un nuevo rechazo tras reproceso (conteo mayor) sí se registra.
    CONSTRAINT uq_audit_dead_letter UNIQUE (message_id, source_queue, death_count)
);
CREATE INDEX idx_audit_dead_letters_queue ON audit_dead_letters(source_queue, id);
